[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
score_betting_game = "Hh7LpaGrzLMMk9NgpFkw99wHE94rQKtfCymxvBm89mgr"

[programs.localnet]
score_betting_game = "Hh7LpaGrzLMMk9NgpFkw99wHE94rQKtfCymxvBm89mgr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/snndmaa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
